### ISSUE TITLE
EOL PCA9505

### ISSUE THREAD

**Issue by kfessel** [ZackFreedman/MiRage#2]
I just saw your Youtube Video. and when you talked about the price of a second MCU i thought to check the price the io expander you use only to find it is marked as EOL

https://www.mouser.de/ProductDetail/NXP-Semiconductors/PCA9505DGG112

maybe the PCA9698DGG is an drop-in replacement

**Comment by ModProg** [comment]
For some reason the link does not work,  maybe try this one: https://www.mouser.de/ProductDetail/NXP-Semiconductors/PCA9505DGG112?qs=sGAEpiMZZMutXGli8Ay4kAfwW%2F5bhnYTM19g8yHTDPI%3D

**Comment by kfessel** [comment]
i am sorry for the noise
The number after the DDG, which is the chip package, indicates the manufacturer packaging:
- 118: meaning non-dry packed reel this is what is going to go
- there is a new packaging DDGY which is dry packed reel (it has just a long lead time)

**Comment by ZackFreedman** [comment]
Thanks for your vigilance. I was aware of the EOL status of the package sold on Digikey and Mouser, and I've already reached out to NXP to verify that the part will remain available in different packaging. Now to decide whether to tie up a few thousand bucks on a purchase commitment 18 months before I know if the project will sell...
