### ISSUE TITLE
Possible STL or other 3d file type for the keyboard because I and I would assume oteh

### ISSUE THREAD

**Issue by PetraSpaceRock** [ZackFreedman/MiRage#5]
because I and I would assume others would likely like to have the ability to do 3D modeling with it without having to install a ton of plugins or use expensive 3D modeling software 
Thanks for the sick Idea tho

**Comment by ZackFreedman** [comment]
STL files are in [the 'Models' directory](https://github.com/ZackFreedman/MiRage/tree/main/Models.)
